### ISSUE TITLE
chapter4b-jwt/jwt.go

### ISSUE THREAD

**Issue by mammenj** [titpetric/books#3]
Found an issue in this code chapter4b-jwt/jwt.go
`undefined: jwtauth.Claims`

**Comment by titpetric** [comment]
The jwtauth claims have been updated since the article was written (2018).
The current implementation has:


   - func SetExpiry(claims jwt.MapClaims, tm time.Time)
   <https://godoc.org/github.com/go-chi/jwtauth#SetExpiry>
   - func SetExpiryIn(claims jwt.MapClaims, tm time.Duration)
   <https://godoc.org/github.com/go-chi/jwtauth#SetExpiryIn>
   - func SetIssuedAt(claims jwt.MapClaims, tm time.Time)
   <https://godoc.org/github.com/go-chi/jwtauth#SetIssuedAt>
   - func SetIssuedNow(claims jwt.MapClaims)
   <https://godoc.org/github.com/go-chi/jwtauth#SetIssuedNow>

So, you'd need to create a jwt.MapClaims if you'd want to use these, or
check the Encode() function - it now takes `jwt.Claims` from the upstream
package which jwtauth uses. There's a StandardClaims implementation there:
https://godoc.org/github.com/dgrijalva/jwt-go#StandardClaims - you should
just fill it out and pass it to Encode() and you're good to go.

**Comment by mammenj** [comment]
Thanks, I have the changed the code as follows:
```
func (jwt *JWT) Encode(claims gojwt.MapClaims) string {
	_, tokenString, _ := jwt.tokenAuth.Encode(claims)
	return tokenString

}
```
and changed the debug statement when creating new:
```
log.Println("DEBUG JWT:", jwt.Encode(gojwt.MapClaims{"user_id": 123}))
```
